Update firewall rule creation for GKE (#1225)
## Description

Fix the issue where a firewall rule cannot be created, causing the
workflow to fail.

```
Creating firewall...
failed.
ERROR: (gcloud.compute.firewall-rules.create) Could not fetch resource:
 - The resource 'projects/hazelcast-[33](https://github.com/hazelcast/hazelcast-platform-operator/actions/runs/9976430034/job/27568598506#step:6:34)/global/firewalls/node-port-range' already exists

ERROR: (gcloud.compute.firewall-rules.update) Could not fetch resource:
 - The resource 'projects/hazelcast-33/global/firewalls/node-port-range' is not ready
```